@startuml
'https://plantuml.com/sequence-diagram
skinparam backgroundColor #EEEBDC
skinparam sequence {
ParticipantBorderColor DodgerBlue
ParticipantBackgroundColor DeepSkyBlue
ActorBorderColor DarkGreen
ActorBackgroundColor Green
BoxBorderColor LightBlue
BoxBackgroundColor #F0FFFF
}
skinparam collections {
  BackGroundColor LightBlue
  BorderColor DodgerBlue
}
skinparam database {
  BackgroundColor LightGreen
  BorderColor DarkGreen
}
title Off Command Sequence\n
participant "CSP_Mid\n.LMC" as lmc #Thistle
box "\nMCS\n"
  participant "Mid.CBF\nController" as controller
  participant "Talon\nDX" as tdx
  participant "FPGA Host\nServer (FHS)" as fhs
  participant "Power\nSwitch" as ps
end box
box "\nNetwork\n"
  participant "Network\nSwitch" as switch #Orange
end box
box "\nPower\n"
  participant "PDU\n" as pdu #Orange
end box
box "\nFHS\n"
  participant "FHS\nBMC" as bmc #LightGreen
  participant "FHS\nMaster" as hpsmaster
end box

note over controller            : AdminMode: ON\nOpState: OFF
lmc -> controller               : Off()

group #LightCyan For each FHS:
  controller    ->  fhs         : Off()
  fhs           ->  bmc ++      : Off() 
  bmc           --> fhs --      : success
  
  note over fhs                 : OpState: UNKNOWN

end group

lmc           <--  controller   : Success

@enduml