@startuml
'https://plantuml.com/sequence-diagram
skinparam backgroundColor #EEEBDC
skinparam sequence {
ParticipantBorderColor DodgerBlue
ParticipantBackgroundColor DeepSkyBlue
ActorBorderColor DarkGreen
ActorBackgroundColor Green
BoxBorderColor LightBlue
BoxBackgroundColor #F0FFFF
}
skinparam collections {
  BackGroundColor LightBlue
  BorderColor DodgerBlue
}
skinparam database {
  BackgroundColor LightGreen
  BorderColor DarkGreen
}

legend right
    |=            |= Type        |
    |<#DodgerBlue>| Tango Device |
    |<#LightGreen>| Hardware     |
endlegend

title Off Command Sequence\n
participant "CSP_Mid\n.LMC" as lmc #Thistle
box "\nMCS\n"
  participant "Mid.CBF\nController" as controller
  participant "Talon\nDX" as tdx
  participant "FPGA Host\nServer (FHS)" as fhs
  participant "Power\nSwitch" as ps
end box
box "\nNetwork\n"
  participant "Network\nSwitch" as switch #LightGreen
end box
box "\nPower\n"
  participant "PDU\n" as pdu #LightGreen
end box
box "\nFHS\n"
  participant "FHS\nBMC" as bmc #LightGreen
  participant "FHS\nController" as hpsmaster
end box

note over controller            : AdminMode: ON\nOpState: OFF
note over pdu                 : PDU is controlled\noutside of MCS

lmc -> controller ++            : Off()

loop #LightCyan each FHS
  controller    ->  fhs++     : Off()
  fhs           ->  bmc++     : Off() 
  alt#Gold  #LightCyan BMC Off() successful
      fhs   <-- bmc--         : success
      rnote over fhs
        OpState: OFF
        HealthState: OK(?)
      end rnote
  else #LightSalmon BMC Off() failed
      rnote over fhs
        OpState: UNKNOWN
        HealthState: FAILED(?)
      end rnote
  end
  controller  <-- fhs--      : Result
end loop

lmc  <--  controller--         : Success

@enduml