image: $SKA_K8S_TOOLS_BUILD_DEPLOY

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  MINIKUBE: "false"
  SHARED_K8S_CHART: "ska-mid-cbf-mcs"
  SERVICE_ACCOUNT: "ci-svc-$CI_PROJECT_NAME-$CI_JOB_ID"
  K8S_TIMEOUT: 500s
  KUBE_NAMESPACE: "ci-$CI_PROJECT_NAME-$CI_PIPELINE_ID"

stages:
  - lint
  - build
  - test
  - deploy
  - integration
  - staging
  - join-reports
  - pages
  - publish
  - scan

# Include CI templates
include:
# OCI Images
# do a custom set of build and publish stages
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/oci-image.gitlab-ci.yml'

# Python packages build,lint, test and publish
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/python.gitlab-ci.yml'

# Jupyter notebook linting and testing
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/notebook.gitlab-ci.yml'

# Helm Charts
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/helm-chart.gitlab-ci.yml'

# Docs pages
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/docs.gitlab-ci.yml'

# .post step finalisers eg: badges
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/finaliser.gitlab-ci.yml'

# k8s steps
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/k8s.gitlab-ci.yml'

# changelog release page
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/changelog.gitlab-ci.yml'

# deploy steps
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/deploy.gitlab-ci.yml'

# release steps
  - project: 'ska-telescope/templates-repository'
    file: 'gitlab-ci/includes/release.gitlab-ci.yml'

k8s-test:
  variables:
    KUBE_NAMESPACE: "ci-$CI_PROJECT_NAME-$CI_PIPELINE_ID"
  before_script:
    - make k8s-namespace
    - make k8s-namespace-credentials
    - make k8s-install-chart
    - make k8s-wait

stop-k8s-test:
  variables:
    KUBE_NAMESPACE: "ci-$CI_PROJECT_NAME-$CI_PIPELINE_ID"

helm-chart-lint:
  allow_failure: true

notebook-lint:
  allow_failure: true

notebook-test:
  rules:
    - when: never

deploy-dev-environment:
  variables:
    KUBE_NAMESPACE: "ci-dev-$CI_PROJECT_NAME-$CI_PIPELINE_ID"
  environment:
    name: ci-dev-$CI_PROJECT_NAME-$CI_COMMIT_REF_NAME

test-dev-environment:
  variables:
    KUBE_NAMESPACE: "ci-dev-$CI_PROJECT_NAME-$CI_PIPELINE_ID"
  environment:
    name: ci-dev-$CI_PROJECT_NAME-$CI_COMMIT_REF_NAME

info-dev-environment:
  variables:
    KUBE_NAMESPACE: "ci-dev-$CI_PROJECT_NAME-$CI_PIPELINE_ID"
  environment:
    name: ci-dev-$CI_PROJECT_NAME-$CI_COMMIT_REF_NAME

stop-dev-environment:
  variables:
    KUBE_NAMESPACE: "ci-dev-$CI_PROJECT_NAME-$CI_PIPELINE_ID"
  environment:
    name: ci-dev-$CI_PROJECT_NAME-$CI_COMMIT_REF_NAME