version: "2.2"

services:
  cbf_dsconfig:
    image: nexus.engageska-portugal.pt/ska-docker/tango-dsconfig:latest
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}cbf_dsconfig
    depends_on:
      - databaseds
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=60 --strict --
             json2tango -w -a -u tangods/tangods/data/midcbf_dsconfig.json  && sleep infinity"
    volumes:
      - .:/tangods
  vcc001:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/${PROJECT}:latest
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}vcc001
    depends_on:
      - databaseds
      - cbf_dsconfig
      - rsyslog
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=60 --strict --
             retry --max=5 -- tango_admin --ping-device mid_csp_cbf/fsp/01 &&\
             retry --max=5 -- tango_admin --ping-device mid_csp_cbf/fsp/02 &&\
             retry --max=5 -- tango_admin --ping-device mid_csp_cbf/fsp/03 &&\
             retry --max=5 -- tango_admin --ping-device mid_csp_cbf/fsp/04 &&\
             /venv/bin/python /app/tangods/Vcc/VccMulti/VccMulti.py vcc-001"

  vcc002:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/${PROJECT}:latest
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}vcc002
    depends_on:
      - databaseds
      - cbf_dsconfig
      - rsyslog
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=60 --strict --
             retry --max=5 -- tango_admin --ping-device mid_csp_cbf/fsp/01 &&\
             retry --max=5 -- tango_admin --ping-device mid_csp_cbf/fsp/02 &&\
             retry --max=5 -- tango_admin --ping-device mid_csp_cbf/fsp/03 &&\
             retry --max=5 -- tango_admin --ping-device mid_csp_cbf/fsp/04 &&\
             /venv/bin/python /app/tangods/Vcc/VccMulti/VccMulti.py vcc-002"

  vcc003:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/${PROJECT}:latest
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}vcc003
    depends_on:
      - databaseds
      - cbf_dsconfig
      - rsyslog
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=60 --strict --
             retry --max=5 -- tango_admin --ping-device mid_csp_cbf/fsp/01 &&\
             retry --max=5 -- tango_admin --ping-device mid_csp_cbf/fsp/02 &&\
             retry --max=5 -- tango_admin --ping-device mid_csp_cbf/fsp/03 &&\
             retry --max=5 -- tango_admin --ping-device mid_csp_cbf/fsp/04 &&\
             /venv/bin/python /app/tangods/Vcc/VccMulti/VccMulti.py vcc-003"

  vcc004:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/${PROJECT}:latest
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}vcc004
    depends_on:
      - databaseds
      - cbf_dsconfig
      - rsyslog
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=60 --strict --
             retry --max=5 -- tango_admin --ping-device mid_csp_cbf/fsp/01 &&\
             retry --max=5 -- tango_admin --ping-device mid_csp_cbf/fsp/02 &&\
             retry --max=5 -- tango_admin --ping-device mid_csp_cbf/fsp/03 &&\
             retry --max=5 -- tango_admin --ping-device mid_csp_cbf/fsp/04 &&\
             /venv/bin/python /app/tangods/Vcc/VccMulti/VccMulti.py vcc-004"

  fsp01:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/${PROJECT}:latest
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}fsp01
    depends_on:
      - databaseds
      - cbf_dsconfig
      - rsyslog
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=60 --strict --
             /venv/bin/python /app/tangods/Fsp/FspMulti/FspMulti.py fsp-01"

  fsp02:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/${PROJECT}:latest
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}fsp02
    depends_on:
      - databaseds
      - cbf_dsconfig
      - rsyslog
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=60 --strict --
             /venv/bin/python /app/tangods/Fsp/FspMulti/FspMulti.py fsp-02"

  fsp03:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/${PROJECT}:latest
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}fsp03
    depends_on:
      - databaseds
      - cbf_dsconfig
      - rsyslog
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=60 --strict --
             /venv/bin/python /app/tangods/Fsp/FspMulti/FspMulti.py fsp-03"

  fsp04:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/${PROJECT}:latest
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}fsp04
    depends_on:
      - databaseds
      - cbf_dsconfig
      - rsyslog
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=60 --strict --
             /venv/bin/python /app/tangods/Fsp/FspMulti/FspMulti.py fsp-04"

  cbfsubarray01:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/${PROJECT}:latest
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}cbfsubarray01
    depends_on:
      - cbf_dsconfig
      - vcc001
      - vcc002
      - vcc003
      - vcc004
      - rsyslog
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=60 --strict --
             tango_admin --check-device mid_csp_cbf/sw1/01 &&\
             tango_admin --check-device mid_csp_cbf/sw2/01 &&\
             tango_admin --check-device mid_csp_cbf/sub_elt/subarray_01 &&\
             retry --max=5 -- tango_admin --ping-device mid_csp_cbf/sub_elt/master &&\
             /venv/bin/python /app/tangods/CbfSubarray/CbfSubarrayMulti/CbfSubarrayMulti.py cbfSubarray-01"

  cbfsubarray02:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/${PROJECT}:latest
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}cbfsubarray02
    depends_on:
      - cbf_dsconfig
      - vcc001
      - vcc002
      - vcc003
      - vcc004
      - rsyslog
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=60 --strict --
             tango_admin --check-device mid_csp_cbf/sw1/02 &&\
             tango_admin --check-device mid_csp_cbf/sw2/02 &&\
             tango_admin --check-device mid_csp_cbf/sub_elt/subarray_02 &&\
             retry --max=5 -- tango_admin --ping-device mid_csp_cbf/sub_elt/master &&\
             /venv/bin/python /app/tangods/CbfSubarray/CbfSubarrayMulti/CbfSubarrayMulti.py cbfSubarray-02"

  cbfmaster:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/${PROJECT}:latest
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}cbfmaster
    depends_on:
      - databaseds
      - cbf_dsconfig
      - vcc001
      - vcc002
      - vcc003
      - vcc004
      - rsyslog
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=60 --strict --
             tango_admin --check-device mid_csp_cbf/sub_elt/master &&\
             retry --max=5 -- tango_admin --ping-device mid_csp_cbf/vcc/001 &&\
             retry --max=5 -- tango_admin --ping-device mid_csp_cbf/vcc/002 &&\
             retry --max=5 -- tango_admin --ping-device mid_csp_cbf/vcc/003 &&\
             retry --max=5 -- tango_admin --ping-device mid_csp_cbf/vcc/004 &&\
             /venv/bin/python /app/tangods/CbfMaster/CbfMaster/CbfMaster.py master"

  tmcspsubarrayleafnodetest:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/${PROJECT}:latest
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}tmcspsubarrayleafnodetest
    depends_on:
      - databaseds
      - cbf_dsconfig
      - cbfmaster
      - rsyslog
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=60 --strict --
             tango_admin --check-device ska_mid/tm_leaf_node/csp_subarray_01 &&\
             /venv/bin/python /app/tangods/TmCspSubarrayLeafNodeTest/TmCspSubarrayLeafNodeTest.py tm"

  tmcspsubarrayleafnodetest2:
    image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_USER}/${PROJECT}:latest
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}tmcspsubarrayleafnodetest2
    depends_on:
      - databaseds
      - cbf_dsconfig
      - cbfmaster
      - rsyslog
    environment:
      - TANGO_HOST=${TANGO_HOST}
    command: >
      sh -c "wait-for-it.sh ${TANGO_HOST} --timeout=60 --strict --
             tango_admin --check-device ska_mid/tm_leaf_node/csp_subarray_02 &&\
             /venv/bin/python /app/tangods/TmCspSubarrayLeafNodeTest/TmCspSubarrayLeafNodeTest.py tm2"


  rsyslog:
    image: jumanjiman/rsyslog
    network_mode: ${NETWORK_MODE}
    container_name: ${CONTAINER_NAME_PREFIX}rsyslog
