@startuml
'https://plantuml.com/sequence-diagram

skinparam backgroundColor #EEEBDC
skinparam sequence {
  ParticipantBorderColor DodgerBlue
  ParticipantBackgroundColor DeepSkyBlue
  ActorBorderColor DarkGreen
  ActorBackgroundColor Green
  BoxBorderColor LightBlue
  BoxBackgroundColor #F0FFFF
}

skinparam collections {
  BackGroundColor LightBlue
  BorderColor DodgerBlue
}

skinparam database {
  BackgroundColor LightGreen
  BorderColor DarkGreen
}

title Abort Command Sequence - Correlation

participant "CSP_Mid\n.LMC" as lmc #Thistle
box "\nMCS\n"
  participant "Mid.CBF\nSubarray" as subarray
  collections "VCC\n" as vcc
  collections "FSP\n" as fsp
  collections "FSP Corr\nSubarray" as fspsubarray
end box
box "\nHPS\n"
  participant "VCC\nController" as hpsvcc
  participant "VCC\nBand1&2" as hpsvccband
  participant "FSP Corr\nController" as hpsfspcorr
end box

lmc        ->  subarray      : Abort
note over subarray           : ObsState: ABORTING
subarray   ->  vcc           : Abort
note over vcc                : ObsState: ABORTING
vcc        ->  hpsvccband    : Abort (stub) 
note over hpsvccband         : (TBD)
note over vcc                : ObsState: ABORTED
subarray   ->  fspsubarray   : Abort
note over fspsubarray        : ObsState: ABORTING
fspsubarray->  hpsfspcorr    : Abort (stub)
note over hpsfspcorr         : (TBD)
note over fspsubarray        : ObsState: ABORTED
note over subarray           : ObsState: ABORTED

lmc       <--  subarray      : Success

@enduml