@startuml
'https://plantuml.com/sequence-diagram

skinparam backgroundColor #EEEBDC
skinparam sequence {
    ParticipantBorderColor DodgerBlue
    ParticipantBackgroundColor DeepSkyBlue
    ActorBorderColor DarkGreen
    ActorBackgroundColor Green
    BoxBorderColor LightBlue
    BoxBackgroundColor #F0FFFF
}
skinparam collections {
    BackGroundColor LightBlue
    BorderColor DodgerBlue
}

title HPS Configure FSP for Correlation Scan\n

box "MCS"
participant "FSP Corr\nSubarray\n" as fspcorr
end box

box "HPS"
participant "FSP Corr\nController\n" as hpsfspcorr
collections "Packet\nStream\nRepair" as psr
collections "Resampler\nDelay\nTracker" as rdt
collections "Fine\nChannelizer\n" as channelizer
collections "DDR4\nCorner\nTurner" as dct
participant "Correlator\n\n" as correlator
end box

group #LightCyan For each FSP in use:
    fspcorr     -> hpsfspcorr   : ConfigureScan(json_str)

    group #LightCyan For each assigned receptor:
        hpsfspcorr  -> psr         : write packet rate
        hpsfspcorr  -> rdt         : stop
        hpsfspcorr  -> rdt         : write attributes
        hpsfspcorr  -> rdt         : set input sample rate
        hpsfspcorr  -> rdt         : start
        hpsfspcorr  -> channelizer : write gain
    end group

    group #LightCyan For each corner turner:
        hpsfspcorr  -> dct  : read number of samples
        hpsfspcorr  -> dct  : write attributes
        hpsfspcorr  -> dct  : subscribe antena_status
    end group

    hpsfspcorr  -> correlator   : write attributes
    hpsfspcorr  -> correlator   : program long term accumulator
    note over hpsfspcorr        : ObsState == READY
    hpsfspcorr  --> fspcorr     : Success
end group

@enduml