@startuml
'https://plantuml.com/sequence-diagram

skinparam backgroundColor #EEEBDC
skinparam sequence {
ParticipantBorderColor DodgerBlue
ParticipantBackgroundColor DeepSkyBlue
ActorBorderColor DarkGreen
ActorBackgroundColor Green
BoxBorderColor LightBlue
BoxBackgroundColor #F0FFFF
}

title HPS Configure FSP for PST Beamforming Scan\n

box "MCS"
participant "Fsp PST\nSubarray" as fsppst
end box

box "HPS"
participant "FSP\nPST" as hpsfsppst
participant "PST 4K\nChannelizer" as channelizer
participant "Packet Stream\nRepair" as psr
participant "Resampler\nDelay Tracker" as rdt
participant "Beam\nSummer" as summer
participant "PST\nPacketizer" as packetizer

end box

fsppst     -> hpsfsppst   : ConfigureScan(json_str)
hpsfsppst  -> psr         : write packet rate
hpsfsppst  -> rdt         : stop
hpsfsppst  -> rdt         : write attributes
hpsfsppst  -> rdt         : set input sample rate
hpsfsppst  -> rdt         : set frequency shifts
hpsfsppst  -> rdt         : start
hpsfsppst  -> channelizer : write gain([..])
hpsfsppst  -> summer      : write enable([..])
hpsfsppst  -> packetizer  : reset_packetizer
hpsfsppst  -> packetizer  : write attributes

@enduml