@startuml
'https://plantuml.com/sequence-diagram
skinparam backgroundColor #EEEBDC
skinparam sequence {
ParticipantBorderColor DodgerBlue
ParticipantBackgroundColor DeepSkyBlue
ActorBorderColor DarkGreen
ActorBackgroundColor Green
BoxBorderColor LightBlue
BoxBackgroundColor #F0FFFF
}
skinparam collections {
  BackGroundColor LightBlue
  BorderColor DodgerBlue
}
skinparam responseMessageBelowArrow true

title InitSysParam Command Sequence\n

participant "CSP_Mid\n.LMC" as lmc #Thistle
box "\nMCS\n"
  participant "Mid.CBF\nController" as controller
  collections "Mid.CBF\nSubarray" as subarray
  collections "VCC\n" as vcc
end box
participant "CAR\n" as car #YellowGreen

lmc          -> controller           : InitSysParam(json_str)
controller      -> controller           : validate JSON \nagainst schema

group #SeaShell If JSON is valid:
  group #SeaShell If URI provided:
    controller      -> car            : retrieve init sys param file
    controller      -> controller     : validate JSON \nagainst schema
  end group
  controller      -> controller     : store sys_param
  controller      -> subarray       : write sys_param (json_str)
  subarray     -> subarray          : store sys_param
  controller      -> vcc            : set dish ID
  lmc         <-- controller        : Success
end group


@enduml