@startuml
'https://plantuml.com/sequence-diagram
skinparam backgroundColor #EEEBDC
skinparam sequence {
ParticipantBorderColor DodgerBlue
ParticipantBackgroundColor DeepSkyBlue
ActorBorderColor DarkGreen
ActorBackgroundColor Green
BoxBorderColor LightBlue
BoxBackgroundColor #F0FFFF
}
skinparam collections {
  BackGroundColor LightBlue
  BorderColor DodgerBlue
}
skinparam responseMessageBelowArrow true
title InitSysParam Command Sequence\n
participant "CSP_Mid\n.LMC" as lmc #Thistle
box "MCS"
participant "Mid.CBF\nController" as control
collections "Mid.CBF\nSubarray" as subarray
collections "VCC" as vcc
end box
participant "CAR" as car #YellowGreen
lmc          -> control           : InitSysParam(json_str)

control      -> control           : validate JSON \nagainst schema

group #SeaShell If JSON is valid:
group #SeaShell If URI provided:
control      -> car               : retrieve init sys param file
control      -> control           : validate JSON \nagainst schema
end
control      -> control           : store sys_param
control      -> subarray          : write sys_param (json_str)
subarray     -> subarray          : store sys_param
control      -> vcc               : set dish ID
lmc         <-- control           : Success

end


@enduml