@startuml
'https://plantuml.com/sequence-diagram
skinparam backgroundColor #EEEBDC
skinparam sequence {
ParticipantBorderColor DodgerBlue
ParticipantBackgroundColor DeepSkyBlue
ActorBorderColor DarkGreen
ActorBackgroundColor Green
BoxBorderColor LightBlue
BoxBackgroundColor #F0FFFF
}
skinparam collections {
  BackGroundColor LightBlue
  BorderColor DodgerBlue
}
skinparam responseMessageBelowArrow true
title InitSysParam Command Sequence\n
participant "CSP_Mid\n.LMC" as lmc
box "MCS"
participant "Mid.CBF\nController" as control
collections "Mid.CBF\nSubarray" as subarray
collections "VCC" as vcc
end box
participant "CAR" as car
note over control                 : OpState: OFF
lmc          -> control           : InitSysParam(\nJSON str)
control      -> control           : check OpState is OFF

alt OpState is OFF
control      -> control           : check JSON is compliant \nwith schema

alt #LightBlue JSON is compliant
alt #DeepSkyBlue URI provided
control      -> car               : retrieve init sys param file
end
control      -> control           : store sys_param
control      -> subarray          : write sys_param (json str)
subarray     -> subarray          : store sys_param
control      -> vcc               : set receptor ID
lmc         <-- control           : Success
else JSON is not compliant
lmc         <-- control           : Fail
end

else OpState is not OFF
lmc         <-- control           : Fail
end
@enduml