@startuml
'https://plantuml.com/sequence-diagram

skinparam backgroundColor #EEEBDC
skinparam sequence {
ParticipantBorderColor DodgerBlue
ParticipantBackgroundColor DeepSkyBlue
ActorBorderColor DarkGreen
ActorBackgroundColor Green
BoxBorderColor LightBlue
BoxBackgroundColor #F0FFFF
}

title TMC and Mid_CBF.LMC Scan Sequence - High Level

participant "TMC\n" as tmc #Gold
participant "CSP_Mid\n.LMC" as lmc #Thistle

box "\nMCS\n"
participant "Mid.CBF\nController" as controller
participant "Mid.CBF\nSubarray" as subarray
end box

note over controller        : OpState: DISABLE
note over subarray          : OpState: DISABLE
group #LemonChiffon If setting SimulationMode to FALSE
    lmc         -> controller   : Update simulationMode
end group
lmc         -> controller   : AdminMode.ONLINE
controller  -> subarray     : SimulationMode
controller  -> subarray     : AdminMode.ONLINE
note over subarray          : OpState: ON
note over controller        : OpState: OFF

lmc         -> controller   : InitSysParam(json_str)
controller --> lmc          : Success

lmc         -> controller   : On()
note over controller        : OpState: ON
controller --> lmc          : Success

lmc         -> subarray     : AddReceptors(list[str])
note over lmc               : Note: adds receptors without duplicates
note over subarray          : ObsState: IDLE
subarray   --> lmc          : Success

lmc         -> subarray     : ConfigureScan(json_str)


group #LemonChiffon Delay model subscription point
    subarray    -> tmc          : Unsubscribe all events
    subarray    -> tmc          : Subscribe delay model
end group

' group Doppler subscription point
' subarray    -> tmc          : subscribe Doppler phase correction
' end group

' group Jones matrix subscription point
' subarray    -> tmc          : subscribe Jones matrix
' end group

' group Timing beam subscription point
' subarray    -> tmc          : subscribe timing beam weights
' end group

note over subarray          : ObsState: READY
subarray   --> lmc          : Success

lmc         -> subarray     : Scan()
note over subarray          : ObsState: SCANNING
subarray   --> lmc          : Success

lmc         -> subarray     : EndScan()
note over subarray          : ObsState: READY
subarray   --> lmc          : Success

lmc         -> subarray     : GoToIdle()
note over subarray          : ObsState: IDLE
subarray   --> lmc          : Success

lmc         -> subarray     : RemoveAllReceptors()
note over subarray          : ObsState: EMPTY
subarray   --> lmc          : Success

lmc         -> controller   : Off()
note over controller        : OpState: OFF
controller --> lmc          : Success

lmc         -> controller   : AdminMode.OFFLINE
controller  -> subarray     : AdminMode.OFFLINE
note over subarray          : OpState: DISABLE
note over controller        : OpState: DISABLE

@enduml