@startuml
'https://plantuml.com/sequence-diagram
skinparam backgroundColor #EEEBDC
skinparam sequence {
ParticipantBorderColor DodgerBlue
ParticipantBackgroundColor DeepSkyBlue
ActorBorderColor DarkGreen
ActorBackgroundColor Green
BoxBorderColor LightBlue
BoxBackgroundColor #F0FFFF
}
skinparam collections {
  BackGroundColor LightBlue
  BorderColor DodgerBlue
}
skinparam database {
  BackgroundColor LightGreen
  BorderColor DarkGreen
}
title Off Command Sequence - Correlation\n
participant "CSP_Mid\n.LMC" as lmc
box "MCS"
participant "Mid.CBF\nController" as controller
participant "Mid.CBF\nSubarray" as subarray
participant "Talon\nBoard" as talon_board
participant "Talon\nLRU" as lru
participant "Power\nSwitch" as switch
participant "SLIM\nFS" as slim_fs
participant "SLIM\nVis" as slim_vis
collections "SLIM\nLink" as slimlink
end box
participant "PDU\n" as pdu
box "HPS"
participant "Linux\nOS" as os #LightGreen
participant "HPS\nMaster" as hpsmaster
collections "HPS\nDevices" as hpsdevices
end box

lmc -> controller : Off()

note over controller         : Clean up observing model:

loop Until Subarray ObsState EMPTY or time exceeded
alt
else ObStates RESOURCING, RESTARTING, ABORTING, \nREADY, RESETTING, SCANNING
controller -> subarray   : Abort
end

controller -> subarray   : Restart
end loop

note over subarray       : Subarray\nObsState EMPTY
controller ->  slim_fs       : Off
slim_fs    ->  slim_fs       : PowerState OFF
slim_fs    ->  slimlink      : Disconnect Links

group SLIM FS Link
slimlink   ->  hpsdevices    : DisconnectTxRx
end 

controller ->  slim_vis      : Off
slim_vis   ->  slim_vis      : PowerState OFF
slim_vis   ->  slimlink      : Disconnect Links


group SLIM Vis Link
slimlink   ->  hpsdevices    : DisconnectTxRx
end

controller ->  talon_board   : Off
controller ->  hpsmaster     : Shutdown(3)
group no Tango exception on Shutdown
hpsmaster  ->  hpsdevices !! : kill pid
hpsmaster  ->  os !!         : system "shutdown now"
controller ->  controller    : wait 4 sec
end group
controller ->  lru           : Off
lru        ->  switch        : Off
switch     ->  pdu           : Off(outlets)

controller ->  controller    : PowerState OFF

@enduml