@startuml
'https://plantuml.com/sequence-diagram

skinparam backgroundColor #EEEBDC
skinparam sequence {
ParticipantBorderColor DodgerBlue
ParticipantBackgroundColor DeepSkyBlue
ActorBorderColor DarkGreen
ActorBackgroundColor Green
BoxBorderColor LightBlue
BoxBackgroundColor #F0FFFF
}

skinparam collections {
  BackGroundColor LightBlue
  BorderColor DodgerBlue
}

skinparam database {
  BackgroundColor LightGreen
  BorderColor DarkGreen
}

title Restart Command Sequence\n

participant "CSP_Mid\n.LMC" as lmc

box "MCS"
participant "Mid.CBF\nSubarray" as subarray
collections "VCC" as vcc
collections "FSP" as fsp
collections "FSP\nCorr\nSubarray" as fspsubarray
end box

box "HPS"
participant "HPS\nVCC\nController" as hpsvcc
participant "HPS\nVCC\nBand1&2" as hpsvccband
participant "HPS FSP\nCorr App" as hpsfsp
collections "HPS\nLow Level\nDevices" as hpsdevices
end box

lmc         ->  subarray      : Restart

subarray    ->  subarray      : deconfigure
subarray    ->  subarray      : remove_all_receptors
subarray    ->  vcc           : ObsReset
vcc         ->  hpsvccband    : ObsReset
note over vcc                 : VCC\nObsState IDLE
subarray    ->  fspsubarray   : ObsReset
note over fspsubarray         : FSP Corr Subarray\nObsState IDLE
subarray    ->  fsp           : RemoveSubarrayMembership

group no other subarray membership
fsp         ->  fspsubarray   : GoToIdle\n
end group

note over fspsubarray         : FSP Corr Subarray\nObsState IDLE
note over subarray            : Subarray\nObsState EMPTY
lmc        <--  subarray      : Success


@enduml