@startuml
'https://plantuml.com/sequence-diagram

skinparam backgroundColor #EEEBDC
skinparam sequence {
ParticipantBorderColor DodgerBlue
ParticipantBackgroundColor DeepSkyBlue
ActorBorderColor DarkGreen
ActorBackgroundColor Green
BoxBorderColor LightBlue
BoxBackgroundColor #F0FFFF
}

skinparam collections {
  BackGroundColor LightBlue
  BorderColor DodgerBlue
}

skinparam database {
  BackgroundColor LightGreen
  BorderColor DarkGreen
}

title Restart Command Sequence - Correlation\n

participant "CSP_Mid\n.LMC" as lmc

box "MCS"
participant "Mid.CBF\nSubarray" as subarray
collections "VCC" as vcc
collections "FSP" as fsp
collections "FSP\nCorr\nSubarray" as fspsubarray
end box

box "HPS"
participant "HPS\nVCC\nController" as hpsvcc
participant "HPS\nVCC\nBand1&2" as hpsvccband
participant "HPS FSP\nCorr App" as hpsfsp
collections "HPS\nLow Level\nDevices" as hpsdevices
end box

lmc         ->  subarray      : Restart

group if subarray in ObsState.FAULT
subarray    ->  vcc           : Abort
vcc         ->  hpsvccband    : Abort (stub)
subarray    <--  vcc          : Success
note over hpsvccband          : (TBD)
note over vcc                 : VCC\nObsState ABORTED
subarray    ->  fspsubarray   : Abort
fspsubarray ->  hpsfsp        : Abort (stub)
note over hpsfsp              : (TBD)
note over fspsubarray         : FSP Corr Subarray\nObsState ABORTED
subarray    <--  fspsubarray  : Success
end group

subarray    ->  vcc           : ObsReset
vcc         ->  hpsvccband    : ObsReset (stub)
note over hpsvccband          : (TBD)
note over vcc                 : VCC\nObsState IDLE
subarray    <--  vcc          : Success

subarray    ->  fspsubarray   : ObsReset
fspsubarray ->  hpsfsp        : ObsReset (stub)
note over hpsfsp              : (TBD)
note over fspsubarray         : FSP Corr Subarray\nObsState IDLE
subarray    <--  fspsubarray  : Success

subarray    ->  subarray      : deconfigure
subarray    ->  fsp           : RemoveSubarrayMembership

group no other subarray membership
fsp         ->  fspsubarray   : AdminMode.OFFLINE\n
note over fsp                 : FSP\nfunctionMode IDLE
note over fsp                 : FSP\nAdminMode.OFFLINE
end group

subarray    <--  fsp          : Success

subarray    ->  vcc           : subarrayMembership = 0
subarray    ->  vcc           : AdminMode.OFFLINE

lmc         <--  subarray     : Success


@enduml