@startuml
'https://plantuml.com/sequence-diagram

skinparam backgroundColor #EEEBDC
skinparam sequence {
ParticipantBorderColor DodgerBlue
ParticipantBackgroundColor DeepSkyBlue
ActorBorderColor DarkGreen
ActorBackgroundColor Green
BoxBorderColor LightBlue
BoxBackgroundColor #F0FFFF
}

title HPS PST Beamforming Scan\n

box "MCS"
participant "Fsp PST\nSubarray" as fsppst
end box

box "HPS"
participant "FSP\nPST" as hpsfsppst
participant "Sync\nBuffer" as buffer
end box

fsppst     -> hpsfsppst   : Scan()
hpsfsppst  -> buffer      : ready_scan()

@enduml