{{ $localchart := . }}

{{- range $key, $deviceServer := $.Values.deviceServers }}

{{- if $deviceServer.enabled }}
{{- $fileDeviceServer := tpl ($.Files.Get (toString $deviceServer.file)) $ | fromYaml }}
{{- $context := dict "deviceserver" $fileDeviceServer "image" $fileDeviceServer.image "local" $localchart }}

{{ template "ska-tango-util.multidevice-config.tpl" $context }}
{{ template "ska-tango-util.multidevice-sacc-role.tpl" $context }}
{{ template "ska-tango-util.multidevice-job.tpl" $context }}
{{ template "ska-tango-util.multidevice-svc.tpl" $context }}

{{- end }}
{{- end }}